spring:
  config:
    activate:
      on-profile: "release"

  initDb:
    enable: false

  datasource:
    url: jdbc:mariadb://nohoo.site:3306/nova?characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy_a310_mariadb
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  com.sehbeomschool.nova: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8080
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ??
    enabled: true

security:
  require-ssl: true
